# Generated by Django 2.1 on 2018-08-28 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import employee.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to=employee.models.user_directory_path)),
                ('biography', models.TextField(blank=True, max_length=500, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='employees', to='company.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
