# Generated by Django 2.1 on 2018-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0003_auto_20180829_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
