# Generated by Django 2.1 on 2018-08-29 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0004_team_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_auto_20180829_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations',
                                              to='company.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
