# Generated by Django 2.1 on 2018-08-29 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0004_team_description'),
        ('employee', '0007_auto_20180829_1641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('company', 'employee')},
        ),
    ]
