# Generated by Django 2.1 on 2018-08-29 19:15

from django.db import migrations, models

import employee.models


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0008_auto_20180829_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=employee.models.user_directory_path),
        ),
    ]
