# Generated by Django 2.1 on 2018-08-29 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0002_auto_20180828_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='admined_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
